"""PreToolUse hook: block Write/Edit on files that must never be edited by hand.

Reads the tool call as JSON from stdin (Claude Code hook protocol), checks the
target ``file_path`` against the protected patterns below and exits with code 2
plus a reason on stderr to block the call. Any other outcome exits 0 (allow).

Protected:
  - propra/graph/*_section_edges.py  -> generated by generate_state_section_edges.py
  - .env                             -> secrets, never modified or committed
"""

import fnmatch
import json
import os
import sys

PROJECT_DIR = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()

# (glob on the project-relative path, exempt globs, reason shown to Claude)
PROTECTED = [
    (
        "propra/graph/*_section_edges.py",
        ["propra/graph/generate_*"],
        "propra/graph/*_section_edges.py sind GENERIERTE Daten und gehören dem "
        "Generator. Nicht von Hand editieren — stattdessen "
        "propra/graph/generate_state_section_edges.py anpassen und neu ausführen.",
    ),
    (
        ".env",
        [],
        ".env enthält Secrets und darf niemals verändert oder committet werden. "
        "Neue Variablen gehören in .env.example (ohne Werte); der Nutzer trägt "
        "die echten Werte selbst in .env ein.",
    ),
]


def to_relative(path: str) -> str:
    """Normalise a tool file path to a forward-slash path relative to the project."""
    path = os.path.abspath(os.path.join(PROJECT_DIR, path))
    try:
        rel = os.path.relpath(path, PROJECT_DIR)
    except ValueError:  # different drive on Windows
        rel = path
    return rel.replace("\\", "/")


def main() -> int:
    # Windows defaults stderr to cp1252, which mangles the German umlauts.
    if hasattr(sys.stderr, "reconfigure"):
        sys.stderr.reconfigure(encoding="utf-8")
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        return 0

    if payload.get("tool_name") not in ("Write", "Edit"):
        return 0

    file_path = (payload.get("tool_input") or {}).get("file_path")
    if not file_path:
        return 0

    rel = to_relative(file_path)
    for pattern, exempt, reason in PROTECTED:
        if not fnmatch.fnmatch(rel, pattern):
            continue
        if any(fnmatch.fnmatch(rel, e) for e in exempt):
            continue
        print(f"BLOCKIERT ({rel}): {reason}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
